---
- block:

    - name: Check for Google Chrome repo
      stat: path=/etc/yum.repos.d/google-chrome.repo
      register: chrome_installed

    - name: Install Google Chrome repo
      dnf:
        name: 'https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm'
        state: present
      when: chrome_installed.stat.exists == False

  when: install_chrome

- block:

    - name: Check for Google Talk repo
      stat: path=/etc/yum.repos.d/google-talkplugin.repo
      register: googletalk_installed

    - name: Install Google Talk repo
      dnf:
        name: 'https://dl.google.com/linux/direct/google-talkplugin_current_x86_64.rpm'
        state: present
      when: googletalk_installed.stat.exists == False

  when: install_googletalk

- block:

    - name: Check for fedora-spotify repo
      stat: path=/etc/yum.repos.d/fedora-spotify.repo
      register: fedora_spotify_installed

    - name: Install fedora-spotify repo
      command: dnf config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo
      when: fedora_spotify_installed.stat.exists == False

  when: install_spotify

- block:

    - name: Check for sublime-text repo
      stat: path=/etc/yum.repos.d/sublime-text.repo
      register: fedora_sublime_text_installed

    - name: Install sublime-text repo
      command: dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
      when: fedora_sublime_text_installed.stat.exists == False

  when: install_sublime_text

- block:

    - name: Check for vscode repo
      stat: path=/etc/yum.repos.d/vscode.repo
      register: fedora_vscode_installed

    - name: Import Microsoft GPG key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Enable vscode repo
      yum_repository:
        name: code
        description: Visual Studio Code
        file: vscode
        baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
        gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
        gpgcheck: yes
      when: fedora_vscode_installed.stat.exists == False

  when: install_vscode

- block:

    - name: Check for slack repo
      stat: path=/etc/yum.repos.d/slack.repo
      register: fedora_slack_installed

    - name: Import Slack GPG key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Enable slack repo
      yum_repository:
        name: slack
        description: Slack
        baseurl: 'https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch'
        gpgkey: 'https://slack.com/gpg/slack_pubkey_2019.gpg'
        gpgcheck: yes
        metadata_expire: '300'
        sslverify: yes
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt
      when: fedora_slack_installed.stat.exists == False

  when: install_slack